spring:
  datasource:
    # 운영 DB 연결 풀 설정
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate  # 운영에서는 validate 또는 none 사용
    show-sql: false       # 운영에서는 SQL 로그 비활성화
    properties:
      hibernate:
        format_sql: false # 운영에서는 포맷팅 비활성화

server:
  port: 8080
  # 운영 서버 설정
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    max-connections: 8192
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

logging:
  level:
    org.hibernate.SQL: warn           # SQL 로그 최소화
    org.hibernate.type.descriptor.sql.BasicBinder: warn
    com.tj.tjp: INFO                  # 애플리케이션 로그는 INFO 레벨
    org.springframework.security: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/tjp/application.log
    max-size: 100MB
    max-history: 30

app:
  jwt:
    access-token-ttl: 3600000     # 1시간 (운영에서는 더 짧게)
    refresh-token-ttl: 2592000000 # 30일

  cookie:
    secure: true      # HTTPS 환경에서는 반드시 true
    same-site: None   # 크로스 도메인 요청 시 필요

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized