spring:
  application:
    name: tjp

  datasource:
    # ??? H2 ??? ??
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

    # PostgreSQL? ??? ? ?? ?? ??
     url: ${DB_URL}
     driver-class-name: org.postgresql.Driver
     username: ${DB_USERNAME}
     password: ${DB_PASSWORD}

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update  # ?? ??? create ?? update, ?? ??? none
    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect  # PostgreSQLDialect? ??? ?
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQLDialect? ??? ?
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # Spring Boot 3 ???? ?? ??? ??

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug                     # ?? SQL ?? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # ???? ?????? ???
