spring:
  application:
    name: tjp

  datasource:
    # PostgreSQL
     url: ${DB_URL}
     driver-class-name: org.postgresql.Driver
     username: ${DB_USERNAME}
     password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update  # ?? ??? create ?? update, ?? ??? none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQLDialect? ??? ?
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # Spring Boot 3 ???? ?? ??? ??

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email

  jwt:
    secret: ${JWT_SECRET_KEY}

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug                     # ?? SQL ?? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # ???? ?????? ???
